name: bookora
description: Bookora - application de lecture PDF (Android)
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.7.0
  firebase_auth: ^4.2.0
  google_sign_in: ^6.1.0
  cloud_firestore: ^4.4.0
  firebase_storage: ^11.0.0
  firebase_functions: ^4.0.0
  file_picker: ^5.2.0
  url_launcher: ^6.1.7
  provider: ^6.0.5
  syncfusion_flutter_pdfviewer: ^25.1.35
  http: ^0.13.6

flutter:
  uses-material-design: true
  assets:
    - assets/books/
